============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0
rootdir: /home/jake/Development/exercism-python
configfile: pytest.ini
plugins: mock-3.11.1, reportlog-0.4.0, repeat-0.9.1
collected 7 items

exercises/practice/hangman/hangman_test.py FFFFFFF                       [100%]

=================================== FAILURES ===================================
_____________ HangmanTests.test_after_10_failures_the_game_is_over _____________

self = <hangman_test.HangmanTests testMethod=test_after_10_failures_the_game_is_over>

    def test_after_10_failures_the_game_is_over(self):
        game = Hangman('foo')
    
        for i in range(10):
>           game.guess('x')
E           AttributeError: 'Hangman' object has no attribute 'guess'

exercises/practice/hangman/hangman_test.py:24: AttributeError
________ HangmanTests.test_feeding_a_correct_letter_removes_underscores ________

self = <hangman_test.HangmanTests testMethod=test_feeding_a_correct_letter_removes_underscores>

    def test_feeding_a_correct_letter_removes_underscores(self):
        game = Hangman('foobar')
    
>       game.guess('b')
E       AttributeError: 'Hangman' object has no attribute 'guess'

exercises/practice/hangman/hangman_test.py:35: AttributeError
_____ HangmanTests.test_feeding_a_correct_letter_twice_counts_as_a_failure _____

self = <hangman_test.HangmanTests testMethod=test_feeding_a_correct_letter_twice_counts_as_a_failure>

    def test_feeding_a_correct_letter_twice_counts_as_a_failure(self):
        game = Hangman('foobar')
    
>       game.guess('b')
E       AttributeError: 'Hangman' object has no attribute 'guess'

exercises/practice/hangman/hangman_test.py:48: AttributeError
_______ HangmanTests.test_getting_all_the_letters_right_makes_for_a_win ________

self = <hangman_test.HangmanTests testMethod=test_getting_all_the_letters_right_makes_for_a_win>

    def test_getting_all_the_letters_right_makes_for_a_win(self):
        game = Hangman('hello')
    
>       game.guess('b')
E       AttributeError: 'Hangman' object has no attribute 'guess'

exercises/practice/hangman/hangman_test.py:61: AttributeError
______________ HangmanTests.test_initially_9_failures_are_allowed ______________

self = <hangman_test.HangmanTests testMethod=test_initially_9_failures_are_allowed>

    def test_initially_9_failures_are_allowed(self):
        game = Hangman('foo')
>       self.assertEqual(game.get_status(), hangman.STATUS_ONGOING)
E       AttributeError: 'Hangman' object has no attribute 'get_status'

exercises/practice/hangman/hangman_test.py:12: AttributeError
______________ HangmanTests.test_initially_no_letters_are_guessed ______________

self = <hangman_test.HangmanTests testMethod=test_initially_no_letters_are_guessed>

    def test_initially_no_letters_are_guessed(self):
        game = Hangman('foo')
    
>       self.assertEqual(game.get_masked_word(), '___')
E       AttributeError: 'Hangman' object has no attribute 'get_masked_word'

exercises/practice/hangman/hangman_test.py:18: AttributeError
________ HangmanTests.test_winning_on_last_guess_still_counts_as_a_win _________

self = <hangman_test.HangmanTests testMethod=test_winning_on_last_guess_still_counts_as_a_win>

    def test_winning_on_last_guess_still_counts_as_a_win(self):
        game = Hangman('aaa')
        for ch in 'bcdefghij':
>           game.guess(ch)
E           AttributeError: 'Hangman' object has no attribute 'guess'

exercises/practice/hangman/hangman_test.py:93: AttributeError
=========================== short test summary info ============================
FAILED exercises/practice/hangman/hangman_test.py::HangmanTests::test_after_10_failures_the_game_is_over
FAILED exercises/practice/hangman/hangman_test.py::HangmanTests::test_feeding_a_correct_letter_removes_underscores
FAILED exercises/practice/hangman/hangman_test.py::HangmanTests::test_feeding_a_correct_letter_twice_counts_as_a_failure
FAILED exercises/practice/hangman/hangman_test.py::HangmanTests::test_getting_all_the_letters_right_makes_for_a_win
FAILED exercises/practice/hangman/hangman_test.py::HangmanTests::test_initially_9_failures_are_allowed
FAILED exercises/practice/hangman/hangman_test.py::HangmanTests::test_initially_no_letters_are_guessed
FAILED exercises/practice/hangman/hangman_test.py::HangmanTests::test_winning_on_last_guess_still_counts_as_a_win
============================== 7 failed in 0.05s ===============================
