============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0
rootdir: /home/jake/Development/exercism-python
configfile: pytest.ini
plugins: mock-3.11.1, reportlog-0.4.0, repeat-0.9.1, asyncio-0.21.1
asyncio: mode=strict
collected 25 items

exercises/practice/wordy/wordy_test.py ........F......FF.FFF....         [100%]

=================================== FAILURES ===================================
_______________________ WordyTest.test_missing_operation _______________________

self = <wordy_test.WordyTest testMethod=test_missing_operation>

    def test_missing_operation(self):
        with self.assertRaises(ValueError) as err:
            answer("What is 2 2 minus 3?")
        self.assertEqual(type(err.exception), ValueError)
>       self.assertEqual(err.exception.args[0], "syntax error")
E       AssertionError: 'unknown operation' != 'syntax error'
E       - unknown operation
E       + syntax error

exercises/practice/wordy/wordy_test.py:112: AssertionError
_______________________ WordyTest.test_non_math_question _______________________

self = <wordy_test.WordyTest testMethod=test_non_math_question>

    def test_non_math_question(self):
        with self.assertRaises(ValueError) as err:
            answer("Who is the President of the United States?")
        self.assertEqual(type(err.exception), ValueError)
>       self.assertEqual(err.exception.args[0], "unknown operation")
E       AssertionError: 'syntax error' != 'unknown operation'
E       - syntax error
E       + unknown operation

exercises/practice/wordy/wordy_test.py:68: AssertionError
____________________ WordyTest.test_reject_postfix_notation ____________________

self = <wordy_test.WordyTest testMethod=test_reject_postfix_notation>

    def test_reject_postfix_notation(self):
        with self.assertRaises(ValueError) as err:
            answer("What is 1 2 plus?")
        self.assertEqual(type(err.exception), ValueError)
>       self.assertEqual(err.exception.args[0], "syntax error")
E       AssertionError: 'unknown operation' != 'syntax error'
E       - unknown operation
E       + syntax error

exercises/practice/wordy/wordy_test.py:98: AssertionError
_______________ WordyTest.test_reject_problem_missing_an_operand _______________

self = <wordy_test.WordyTest testMethod=test_reject_problem_missing_an_operand>

    def test_reject_problem_missing_an_operand(self):
        with self.assertRaises(ValueError) as err:
>           answer("What is 1 plus?")

exercises/practice/wordy/wordy_test.py:72: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def answer(question):
        question = question.replace('?', '').replace('by', '')
        words = question.split()
        if words[0] != 'What' or words[1] != 'is':
            raise ValueError("syntax error")
    
        try:
            result = int(words[2])
        except ValueError:
            raise ValueError("syntax error")
    
        i = 3
        while i < len(words):
            operator = words[i]
            if operator not in ['plus', 'minus', 'multiplied', 'divided']:
                raise ValueError("unknown operation")
    
            try:
>               num = int(words[i + 1])
E               IndexError: list index out of range

exercises/practice/wordy/wordy.py:19: IndexError
_________ WordyTest.test_reject_problem_with_no_operands_or_operators __________

self = <wordy_test.WordyTest testMethod=test_reject_problem_with_no_operands_or_operators>

    def test_reject_problem_with_no_operands_or_operators(self):
        with self.assertRaises(ValueError) as err:
>           answer("What is?")

exercises/practice/wordy/wordy_test.py:78: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def answer(question):
        question = question.replace('?', '').replace('by', '')
        words = question.split()
        if words[0] != 'What' or words[1] != 'is':
            raise ValueError("syntax error")
    
        try:
>           result = int(words[2])
E           IndexError: list index out of range

exercises/practice/wordy/wordy.py:8: IndexError
__________________ WordyTest.test_reject_two_numbers_in_a_row __________________

self = <wordy_test.WordyTest testMethod=test_reject_two_numbers_in_a_row>

    def test_reject_two_numbers_in_a_row(self):
        with self.assertRaises(ValueError) as err:
            answer("What is 1 plus 2 1?")
        self.assertEqual(type(err.exception), ValueError)
>       self.assertEqual(err.exception.args[0], "syntax error")
E       AssertionError: 'unknown operation' != 'syntax error'
E       - unknown operation
E       + syntax error

exercises/practice/wordy/wordy_test.py:92: AssertionError
=========================== short test summary info ============================
FAILED exercises/practice/wordy/wordy_test.py::WordyTest::test_missing_operation
FAILED exercises/practice/wordy/wordy_test.py::WordyTest::test_non_math_question
FAILED exercises/practice/wordy/wordy_test.py::WordyTest::test_reject_postfix_notation
FAILED exercises/practice/wordy/wordy_test.py::WordyTest::test_reject_problem_missing_an_operand
FAILED exercises/practice/wordy/wordy_test.py::WordyTest::test_reject_problem_with_no_operands_or_operators
FAILED exercises/practice/wordy/wordy_test.py::WordyTest::test_reject_two_numbers_in_a_row
========================= 6 failed, 19 passed in 0.08s =========================
