============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0
rootdir: /home/jake/Development/exercism-python
configfile: pytest.ini
plugins: mock-3.11.1, reportlog-0.4.0, repeat-0.9.1
collected 17 items

exercises/practice/ocr-numbers/ocr_numbers_test.py FFFFFFFFFFFFFFFF.     [100%]

=================================== FAILURES ===================================
______ OcrNumbersTest.test_garbled_numbers_in_a_string_are_replaced_with _______

self = <ocr_numbers_test.OcrNumbersTest testMethod=test_garbled_numbers_in_a_string_are_replaced_with>

    def test_garbled_numbers_in_a_string_are_replaced_with(self):
>       self.assertEqual(
            convert(
                [
                    "       _     _           _ ",
                    "  |  || |  || |     || || |",
                    "  |  | _|  ||_|  |  ||_||_|",
                    "                           ",
                ]
            ),
            "11?10?1?0",
        )
E       AssertionError: '?????????' != '11?10?1?0'
E       - ?????????
E       + 11?10?1?0

exercises/practice/ocr-numbers/ocr_numbers_test.py:56: AssertionError
_ OcrNumbersTest.test_input_with_a_number_of_columns_that_is_not_a_multiple_of_three_raises_an_error _

self = <ocr_numbers_test.OcrNumbersTest testMethod=test_input_with_a_number_of_columns_that_is_not_a_multiple_of_three_raises_an_error>

    def test_input_with_a_number_of_columns_that_is_not_a_multiple_of_three_raises_an_error(
        self,
    ):
        with self.assertRaises(ValueError) as err:
            convert(["    ", "   |", "   |", "    "])
        self.assertEqual(type(err.exception), ValueError)
>       self.assertEqual(
            err.exception.args[0], "Number of input columns is not a multiple of three"
        )
E       AssertionError: 'Invalid row' != 'Number of input columns is not a multiple of three'
E       - Invalid row
E       + Number of input columns is not a multiple of three

exercises/practice/ocr-numbers/ocr_numbers_test.py:38: AssertionError
_ OcrNumbersTest.test_input_with_a_number_of_lines_that_is_not_a_multiple_of_four_raises_an_error _

self = <ocr_numbers_test.OcrNumbersTest testMethod=test_input_with_a_number_of_lines_that_is_not_a_multiple_of_four_raises_an_error>

    def test_input_with_a_number_of_lines_that_is_not_a_multiple_of_four_raises_an_error(
        self,
    ):
        with self.assertRaises(ValueError) as err:
            convert([" _ ", "| |", "   "])
        self.assertEqual(type(err.exception), ValueError)
>       self.assertEqual(
            err.exception.args[0], "Number of input lines is not a multiple of four"
        )
E       AssertionError: 'Invalid input grid' != 'Number of input lines is not a multiple of four'
E       - Invalid input grid
E       + Number of input lines is not a multiple of four

exercises/practice/ocr-numbers/ocr_numbers_test.py:28: AssertionError
_ OcrNumbersTest.test_numbers_separated_by_empty_lines_are_recognized_lines_are_joined_by_commas _

self = <ocr_numbers_test.OcrNumbersTest testMethod=test_numbers_separated_by_empty_lines_are_recognized_lines_are_joined_by_commas>

    def test_numbers_separated_by_empty_lines_are_recognized_lines_are_joined_by_commas(
        self,
    ):
>       self.assertEqual(
            convert(
                [
                    "    _  _ ",
                    "  | _| _|",
                    "  ||_  _|",
                    "         ",
                    "    _  _ ",
                    "|_||_ |_ ",
                    "  | _||_|",
                    "         ",
                    " _  _  _ ",
                    "  ||_||_|",
                    "  ||_| _|",
                    "         ",
                ]
            ),
            "123,456,789",
        )
E       AssertionError: '???\n???\n???' != '123,456,789'
E       + 123,456,789- ???
E       - ???
E       - ???

exercises/practice/ocr-numbers/ocr_numbers_test.py:108: AssertionError
_______________________ OcrNumbersTest.test_recognizes_0 _______________________

self = <ocr_numbers_test.OcrNumbersTest testMethod=test_recognizes_0>

    def test_recognizes_0(self):
>       self.assertEqual(convert([" _ ", "| |", "|_|", "   "]), "0")
E       AssertionError: '?' != '0'
E       - ?
E       + 0

exercises/practice/ocr-numbers/ocr_numbers_test.py:14: AssertionError
_______________________ OcrNumbersTest.test_recognizes_1 _______________________

self = <ocr_numbers_test.OcrNumbersTest testMethod=test_recognizes_1>

    def test_recognizes_1(self):
>       self.assertEqual(convert(["   ", "  |", "  |", "   "]), "1")
E       AssertionError: '?' != '1'
E       - ?
E       + 1

exercises/practice/ocr-numbers/ocr_numbers_test.py:17: AssertionError
___________________ OcrNumbersTest.test_recognizes_110101100 ___________________

self = <ocr_numbers_test.OcrNumbersTest testMethod=test_recognizes_110101100>

    def test_recognizes_110101100(self):
>       self.assertEqual(
            convert(
                [
                    "       _     _        _  _ ",
                    "  |  || |  || |  |  || || |",
                    "  |  ||_|  ||_|  |  ||_||_|",
                    "                           ",
                ]
            ),
            "110101100",
        )
E       AssertionError: '?????????' != '110101100'
E       - ?????????
E       + 110101100

exercises/practice/ocr-numbers/ocr_numbers_test.py:43: AssertionError
_______________________ OcrNumbersTest.test_recognizes_2 _______________________

self = <ocr_numbers_test.OcrNumbersTest testMethod=test_recognizes_2>

    def test_recognizes_2(self):
>       self.assertEqual(convert([" _ ", " _|", "|_ ", "   "]), "2")
E       AssertionError: '?' != '2'
E       - ?
E       + 2

exercises/practice/ocr-numbers/ocr_numbers_test.py:69: AssertionError
_______________________ OcrNumbersTest.test_recognizes_3 _______________________

self = <ocr_numbers_test.OcrNumbersTest testMethod=test_recognizes_3>

    def test_recognizes_3(self):
>       self.assertEqual(convert([" _ ", " _|", " _|", "   "]), "3")
E       AssertionError: '?' != '3'
E       - ?
E       + 3

exercises/practice/ocr-numbers/ocr_numbers_test.py:72: AssertionError
_______________________ OcrNumbersTest.test_recognizes_4 _______________________

self = <ocr_numbers_test.OcrNumbersTest testMethod=test_recognizes_4>

    def test_recognizes_4(self):
>       self.assertEqual(convert(["   ", "|_|", "  |", "   "]), "4")
E       AssertionError: '?' != '4'
E       - ?
E       + 4

exercises/practice/ocr-numbers/ocr_numbers_test.py:75: AssertionError
_______________________ OcrNumbersTest.test_recognizes_5 _______________________

self = <ocr_numbers_test.OcrNumbersTest testMethod=test_recognizes_5>

    def test_recognizes_5(self):
>       self.assertEqual(convert([" _ ", "|_ ", " _|", "   "]), "5")
E       AssertionError: '?' != '5'
E       - ?
E       + 5

exercises/practice/ocr-numbers/ocr_numbers_test.py:78: AssertionError
_______________________ OcrNumbersTest.test_recognizes_6 _______________________

self = <ocr_numbers_test.OcrNumbersTest testMethod=test_recognizes_6>

    def test_recognizes_6(self):
>       self.assertEqual(convert([" _ ", "|_ ", "|_|", "   "]), "6")
E       AssertionError: '?' != '6'
E       - ?
E       + 6

exercises/practice/ocr-numbers/ocr_numbers_test.py:81: AssertionError
_______________________ OcrNumbersTest.test_recognizes_7 _______________________

self = <ocr_numbers_test.OcrNumbersTest testMethod=test_recognizes_7>

    def test_recognizes_7(self):
>       self.assertEqual(convert([" _ ", "  |", "  |", "   "]), "7")
E       AssertionError: '?' != '7'
E       - ?
E       + 7

exercises/practice/ocr-numbers/ocr_numbers_test.py:84: AssertionError
_______________________ OcrNumbersTest.test_recognizes_8 _______________________

self = <ocr_numbers_test.OcrNumbersTest testMethod=test_recognizes_8>

    def test_recognizes_8(self):
>       self.assertEqual(convert([" _ ", "|_|", "|_|", "   "]), "8")
E       AssertionError: '?' != '8'
E       - ?
E       + 8

exercises/practice/ocr-numbers/ocr_numbers_test.py:87: AssertionError
_______________________ OcrNumbersTest.test_recognizes_9 _______________________

self = <ocr_numbers_test.OcrNumbersTest testMethod=test_recognizes_9>

    def test_recognizes_9(self):
>       self.assertEqual(convert([" _ ", "|_|", " _|", "   "]), "9")
E       AssertionError: '?' != '9'
E       - ?
E       + 9

exercises/practice/ocr-numbers/ocr_numbers_test.py:90: AssertionError
___________ OcrNumbersTest.test_recognizes_string_of_decimal_numbers ___________

self = <ocr_numbers_test.OcrNumbersTest testMethod=test_recognizes_string_of_decimal_numbers>

    def test_recognizes_string_of_decimal_numbers(self):
>       self.assertEqual(
            convert(
                [
                    "    _  _     _  _  _  _  _  _ ",
                    "  | _| _||_||_ |_   ||_||_|| |",
                    "  ||_  _|  | _||_|  ||_| _||_|",
                    "                              ",
                ]
            ),
            "1234567890",
        )
E       AssertionError: '??????????' != '1234567890'
E       - ??????????
E       + 1234567890

exercises/practice/ocr-numbers/ocr_numbers_test.py:93: AssertionError
=========================== short test summary info ============================
FAILED exercises/practice/ocr-numbers/ocr_numbers_test.py::OcrNumbersTest::test_garbled_numbers_in_a_string_are_replaced_with
FAILED exercises/practice/ocr-numbers/ocr_numbers_test.py::OcrNumbersTest::test_input_with_a_number_of_columns_that_is_not_a_multiple_of_three_raises_an_error
FAILED exercises/practice/ocr-numbers/ocr_numbers_test.py::OcrNumbersTest::test_input_with_a_number_of_lines_that_is_not_a_multiple_of_four_raises_an_error
FAILED exercises/practice/ocr-numbers/ocr_numbers_test.py::OcrNumbersTest::test_numbers_separated_by_empty_lines_are_recognized_lines_are_joined_by_commas
FAILED exercises/practice/ocr-numbers/ocr_numbers_test.py::OcrNumbersTest::test_recognizes_0
FAILED exercises/practice/ocr-numbers/ocr_numbers_test.py::OcrNumbersTest::test_recognizes_1
FAILED exercises/practice/ocr-numbers/ocr_numbers_test.py::OcrNumbersTest::test_recognizes_110101100
FAILED exercises/practice/ocr-numbers/ocr_numbers_test.py::OcrNumbersTest::test_recognizes_2
FAILED exercises/practice/ocr-numbers/ocr_numbers_test.py::OcrNumbersTest::test_recognizes_3
FAILED exercises/practice/ocr-numbers/ocr_numbers_test.py::OcrNumbersTest::test_recognizes_4
FAILED exercises/practice/ocr-numbers/ocr_numbers_test.py::OcrNumbersTest::test_recognizes_5
FAILED exercises/practice/ocr-numbers/ocr_numbers_test.py::OcrNumbersTest::test_recognizes_6
FAILED exercises/practice/ocr-numbers/ocr_numbers_test.py::OcrNumbersTest::test_recognizes_7
FAILED exercises/practice/ocr-numbers/ocr_numbers_test.py::OcrNumbersTest::test_recognizes_8
FAILED exercises/practice/ocr-numbers/ocr_numbers_test.py::OcrNumbersTest::test_recognizes_9
FAILED exercises/practice/ocr-numbers/ocr_numbers_test.py::OcrNumbersTest::test_recognizes_string_of_decimal_numbers
========================= 16 failed, 1 passed in 0.09s =========================
